In [1]:
# Set a working directory
#!pip install GitPython
import git
import os

repo = git.Repo('.', search_parent_directories=True)


os.chdir(repo.working_tree_dir)

In [2]:
import pandas as pd

# Training Data
### Our training data is Seaflow cruise data coloquialized with Mercator Pisces nutrient data and sattelite measured salinity and temperature data from Simons CMAP

In [3]:
covari = pd.read_csv('data_ingest/data/modified/RF_ready_covari.csv')

In [4]:
covari.head(10)

,time,cruise,lat,lon,biomass_pro,biomass_syn,biomass_pico,biomass_croco,sss,sst,ugos,vgos,Fe,O2,NO3,PO4,Si,ALK,hours_since_sunrise
0,2015-05-22 22:00:00,KM1508,21.343400,-158.273700,4.024661,0.337763,0.555395,0.009181,34.571716,25.653118,0.005764,-0.132531,0.000088,216.794167,4.269278e-07,0.345151,9.464704,1952.641800,6.129444
1,2015-05-22 23:00:00,KM1508,21.343533,-158.273744,4.167834,0.413687,0.720884,0.013144,34.571716,25.653118,0.005764,-0.132531,0.000088,216.794167,4.269278e-07,0.345151,9.464704,1952.641800,7.129444
2,2015-05-23 00:00:00,KM1508,21.346175,-158.274150,4.654360,0.654208,0.635654,0.008443,34.609317,25.646243,-0.002256,-0.132022,0.000088,216.794167,4.269278e-07,0.345151,9.464704,1952.641800,8.129722
3,2015-05-23 03:00:00,KM1508,21.875350,-158.252225,5.259977,0.216436,0.526369,0.022610,34.626952,25.246660,-0.154771,0.091308,0.000102,217.801038,5.199637e-07,0.350773,9.548164,1953.802750,11.146667
4,2015-05-23 04:00:00,KM1508,22.001275,-158.224300,5.273034,0.340149,0.625376,0.020750,34.626952,25.246660,-0.154771,0.091308,0.000091,218.341288,5.843342e-07,0.353190,9.569982,1952.970325,12.152222
5,2015-05-23 05:00:00,KM1508,22.209583,-158.181517,5.504294,0.356151,0.699834,0.021097,34.723892,25.108327,-0.188260,0.129275,0.000091,218.341288,5.843342e-07,0.353190,9.569982,1952.970325,13.161389
6,2015-05-23 06:00:00,KM1508,22.372667,-158.150067,5.416650,0.328016,0.739331,0.010572,34.723892,25.108327,-0.188260,0.129275,0.000091,218.341288,5.843342e-07,0.353190,9.569982,1954.127925,14.168333
7,2015-05-23 07:00:00,KM1508,22.612250,-158.098550,4.612639,0.161822,0.451722,0.020366,34.901843,24.878743,-0.146975,0.087694,0.000083,218.618786,5.829766e-07,0.352227,9.559466,1954.127925,15.178889
8,2015-05-23 08:00:00,KM1508,22.750000,-158.050250,4.729167,0.155495,0.332936,0.022441,34.919621,24.813327,-0.076290,0.050154,0.000083,218.618786,5.829766e-07,0.352227,9.559466,1954.785450,16.186389
9,2015-05-23 09:00:00,KM1508,22.750000,-158.016250,4.427821,0.167932,0.817730,0.023286,34.919621,24.813327,-0.076290,0.050154,0.000083,218.618786,5.829766e-07,0.352227,9.559466,1954.785450,17.188611

In [5]:
print(covari.shape, '\n', '\n', covari.columns, '\n', '\n', covari.dtypes)

(4680, 19)

 Index(['time', 'cruise', 'lat', 'lon', 'biomass_pro', 'biomass_syn',
       'biomass_pico', 'biomass_croco', 'sss', 'sst', 'ugos', 'vgos', 'Fe',
       'O2', 'NO3', 'PO4', 'Si', 'ALK', 'hours_since_sunrise'],
      dtype='object')

 time                    object
cruise                  object
lat                    float64
lon                    float64
biomass_pro            float64
biomass_syn            float64
biomass_pico           float64
biomass_croco          float64
sss                    float64
sst                    float64
ugos                   float64
vgos                   float64
Fe                     float64
O2                     float64
NO3                    float64
PO4                    float64
Si                     float64
ALK                    float64
hours_since_sunrise    float64
dtype: object

# Prediction Data
### Our prediction data is the same CMAP data, but for every latitude and longitude point that is over the ocean

In [6]:
predictors = pd.read_csv('data_ingest/data/modified/predictors_clean.csv')

In [7]:
predictors.head(10)

,lat,lon,time,sss,sst,ugos,vgos,fe,o2,no3,po4,si,ALK,hours_since_sunrise
0,-73.0,-88.0,2023-04-09 17:23:49,37.974533,-1.331951,-0.040600,-0.031567,0.002671,356.679917,31.386101,1.812338,44.570525,2.298122,4.000000
1,-73.0,-87.0,2023-04-09 17:19:48,37.209843,-1.398338,-0.031342,-0.007600,0.001419,357.710907,30.033035,1.872863,49.430683,2.322180,4.000000
2,-73.0,-86.0,2023-04-09 17:15:47,37.508607,-1.406158,-0.033887,0.025767,0.001165,357.390835,29.585792,1.905870,52.383142,2.330420,4.000000
3,-73.0,-85.0,2023-04-09 17:11:46,37.447979,-1.381464,-0.032660,0.029713,0.001097,357.027335,29.195063,1.921043,53.437034,2.333787,4.000000
4,-73.0,-84.0,2023-04-09 17:07:45,36.873035,-1.395422,-0.021600,0.012412,0.000974,357.010935,28.872238,1.946533,56.603876,2.339559,4.000000
5,-73.0,-83.0,2023-04-09 17:03:44,36.666980,-1.228131,-0.025633,-0.006383,0.000785,359.113269,28.623838,1.932630,55.186904,2.337351,4.000000
6,-73.0,-82.0,2023-04-09 16:59:44,36.379612,-0.983757,-0.022550,-0.026987,0.000858,361.018502,28.771730,1.905424,52.032122,2.332145,4.000278
7,-73.0,-81.0,2023-04-09 16:55:43,35.590419,-0.964799,-0.011700,-0.058146,0.001072,360.742495,29.463827,1.882963,50.821628,2.327281,4.000000
8,-73.0,-80.0,2023-04-09 16:51:42,34.797155,-1.193339,0.016333,-0.065483,0.000999,360.089265,29.634191,1.853181,47.668235,2.324119,4.000000
9,-72.0,-95.0,2023-04-09 17:46:13,32.204678,-1.481466,0.013167,-0.000304,0.001479,359.454686,30.249381,1.850416,46.718758,2.317222,4.000000

In [8]:
print(predictors.shape, '\n', '\n', predictors.columns, '\n', '\n', predictors.dtypes)

(35309, 14)

 Index(['lat', 'lon', 'time', 'sss', 'sst', 'ugos', 'vgos', 'fe', 'o2', 'no3',
       'po4', 'si', 'ALK', 'hours_since_sunrise'],
      dtype='object')

 lat                    float64
lon                    float64
time                    object
sss                    float64
sst                    float64
ugos                   float64
vgos                   float64
fe                     float64
o2                     float64
no3                    float64
po4                    float64
si                     float64
ALK                    float64
hours_since_sunrise    float64
dtype: object